import React from 'react';
import Head from 'next/head';
import { Col, Row } from 'react-bootstrap';
import { useTheme } from 'styled-components';
import FlipCard from '../../components/flip-card.component';

export default function FlipCardPage() {
  const { width } = useTheme();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Row className={width >= 992 ? 'pt-5 m-0 pb-0 pe-0 ps-0' : 'm-0 p-0'}>
        <Col lg={3} xl={3}>
          <FlipCard />
        </Col>
        <Col lg={3} xl={3}>
          <FlipCard />S
        </Col>
      </Row>
    </div>
  );
}