import React from 'react';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { Col, Container, Row } from 'react-bootstrap';
import { useTheme } from 'styled-components';
import FlipCard from '../../../components/flip-card.component';

function App() {
	const { width } = useTheme();
	const { user } = useSelector(({ user }) => user);
	console.log(user);
	return (
		<div>
			<Head>
				<title>Flip Card Game</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container style={{ paddingTop: "5rem" }}>
				<Row style={{ paddingTop: "5rem" }}>
					{user?.studyWords?.map((studyWord, index) => (
						<Col key={index} xs={12} sm={12} md={6} lg={3} xl={3} studyWord={studyWord}>
							<FlipCard />
						</Col>
					))}
				</Row>
			</Container>
		</div>
	)
}

export default React.memo(App);