import React from 'react';
import Head from 'next/head';
import { randomColor } from 'randomcolor';
import { useSelector } from 'react-redux';
import { ProgressBar } from 'react-bootstrap';
import { Col, Container, Row } from 'react-bootstrap';
import FlipCard from '../../../components/flip-card.component';

function GamePage() {
	const { user } = useSelector(({ user }) => user);
	// function count(arr) {
	// 	return arr.reduce((prev, curr) => { 
	// 		console.log(curr)
	// 		return (prev[curr].memoro = ++prev[curr] || 1, prev)
	// 	 }, {})
	// }
	// console.log(count(user?.studyWords))
	return (
		<div>
			<Head>
				<title>Flip Card Game</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container style={{ paddingTop: "5rem" }}>
				<ProgressBar>
					<ProgressBar animated striped variant="success" now={35} key={1} />
					<ProgressBar animated variant="warning" now={20} key={2} />
					<ProgressBar animated striped variant="danger" now={10} key={3} />
				</ProgressBar>
				<Row >
					{user?.studyWords?.map((studyWord, index) => (
						<Col key={index} xs={12} sm={12} md={6} lg={3} xl={3} >
							<FlipCard studyWord={studyWord} color={randomColor({ format: "hex" })} />
						</Col>
					))}
				</Row>
			</Container>
		</div>
	)
}

export default React.memo(GamePage);