import Head from 'next/head';
import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { Container } from 'react-bootstrap';
import { useTheme } from 'styled-components';
import { loadUserWords, loadLanguages } from '../../redux/slices';

function DictionaryPage() {
  const { width } = useTheme();
  const dispatch = useDispatch();

  useEffect(() => {
    localStorage.token &&
      dispatch(loadUserWords({ token: localStorage.token }));
    dispatch(loadLanguages());
  }, []);

  return (
    <div>
      <Head>
        <title>Dictionary</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>Hello there</Container>
      {/* <Container>
        <Row
          className={width >= 992 ? 'pt-5 m-0 pb-0 pe-0 ps-0' : 'm-0 p-0'}
          style={{ backgroundColor: 'red' }}>
          <SideBarHolder xm={12} sm={12} md={12} lg={3} xl={2}>
            <Sidebar />
          </SideBarHolder>
          <LocalizationHolder xm={12} sm={12} md={12} lg={9} xl={10}>
            <LocalizationKeyValueBody />
          </LocalizationHolder>
        </Row>
      </Container> */}
    </div>
  );
}

export default DictionaryPage;
